### ISSUE TITLE
TypeError: Cannot set property 'totals' of undefined

### ISSUE THREAD

**Issue by washington-kibichii** [bahmutov/cypress-json-results#14]
An error is thrown in plugins file while executing the handler for the after:run event.

`  options.on('after:run', (afterRun) => {
    // add the totals to the results
    // explanation of test statuses in the blog post
    // https://glebbahmutov.com/blog/cypress-test-statuses/
    allResults.totals = {
      suites: afterRun.totalSuites,
      tests: afterRun.totalTests,
      failed: afterRun.totalFailed,
      passed: afterRun.totalPassed,
      pending: afterRun.totalPending,
      skipped: afterRun.totalSkipped,
    }`

**Comment by bahmutov** [comment]
What's the cypress version that is causing the problem?
