### ISSUE TITLE
Something doesn't look quite right with default options

### ISSUE THREAD

**Issue by zachlysobey** [bahmutov/cypress-json-results#9]
In the following code, it looks like the *intention* was to merge the defaults into options.

```js
function registerCypressJsonResults(options = {}) {
  const defaults = {
    filename: 'results.json',
  }
  options = { ...options, defaults }
  // ...
}
```

But if you call `registerCypressJsonResults({ filename: 'foo.json' })`, options will end up looking like the following:

```js
{
  filename: 'foo.json',
  defaults: {
    filename: 'results.json',
  }
}
```

I suspect what you *want* to do is something more like this

```js
options = { ...defaults, ...options }
```

notice `defaults` is *first* so any duplicate properties in `options` will override it.

**Comment by bahmutov** [comment]
You are right, fixing
